### ISSUE TITLE
[bug反馈]index.html代码存在报错。

### ISSUE THREAD

**Issue by DeSireFire** [Zfour/Butterfly-gitcalendar#3]
![image](https://user-images.githubusercontent.com/18726905/108625844-01d45900-7488-11eb-930f-8fd3cae5f51f.png)

https://github.com/Zfour/Butterfly-gitcalendar/blob/master/index.html 文件
第230行这里
```text
                        let first1date = calendar.data[47]
                        calendar.monthcoresum += firstdate[6].count
```
变量 "first1date" 好像写多了"1",可能是不小心按到了吧..

**Comment by Zfour** [comment]
修复了，之前去juery的时候忘了改这个html模板了

**Comment by Zfour** [comment]
butterfly主题可参考这篇进行配置：
https://akilar.top/posts/1f9c68c9/

**Comment by DeSireFire** [comment]
> butterfly主题可参考这篇进行配置：[https](https://akilar.top/posts/1f9c68c9/) :
> [//akilar.top/posts/1f9c68c9/](https://akilar.top/posts/1f9c68c9/)

好的！~谢谢Zfour大佬。这个教程我有在看。
感谢Zfour开发了这么多美化插件orz
